### ISSUE TITLE
Missing binaries for firmware 15.04.3

### ISSUE THREAD

**Issue by etix** [Ultimaker/cura-binary-data#1]
A new release of the Ultimaker2Marlin firmware (15.04.3) has been tagged few weeks ago. Can you please update the binaries for the next Cura release?

Thanks a lot.

**Comment by daid** [comment]
This is because the old Cura release was done, which does automatic tagging of the sources. So the binaries for that release can be found in the old cura package. There where no vital changes between these two revisions.

**Comment by etix** [comment]
This is not a major release I agree but still the 15.04.3 firmware brought a fix for the M42 command that I'd like to have as an official binary. Is there any way I can get it without rebuilding the whole firmware myself?

**Comment by daid** [comment]
Extract the latest release from http://software.ultimaker.com/current/

**Comment by etix** [comment]
Oh okay, got it. I thought this repository was used as the head for all Cura releases, but it seems I was wrong. Thanks and sorry for the noise :-)

**Comment by awhiemstra** [comment]
If there are fixes in 15.04.3 then yes, the firmwares here should be updated. This repo contains all "extra" data files that the new Cura should use.
